### ISSUE TITLE
extract version

### ISSUE THREAD

**Issue by priyazsh** [codingstella/Projects-zipfiles#1]
i prefer upload all the source code in a seperate folder with extracted file it can be easy for the user expereince

**Comment by codingstella** [comment]
> i prefer upload all the source code in a seperate folder with extracted file it can be easy for the user expereince

How Brother ?? I didn't Understand What are You Telling ! Are you Telling to Create Separate Repository for all projects...

**Comment by codingstella** [comment]
Ok I will see to it ☺️
